const ISO_DATE_PATTERN = /^(\d{4})-(\d{2})-(\d{2})$/;

/** Formats a date-only value for the UI without applying a timezone conversion. */
export function formatDisplayDate(value?: string | null): string {
  if (!value) return "—";

  const match = ISO_DATE_PATTERN.exec(value);
  return match ? `${match[3]}-${match[2]}-${match[1]}` : value;
}

/** Formats ISO date fragments embedded in labels generated by the application. */
export function formatDatesInText(value: string): string {
  return value.replace(/\b(\d{4})-(\d{2})-(\d{2})\b/g, "$3-$2-$1");
}

export function formatDisplayDateTime(value?: string | null): string {
  if (!value) return "—";

  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return formatDatesInText(value);

  const datePart = new Intl.DateTimeFormat("it-IT", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  }).format(date).replace(/\//g, "-");
  const timePart = new Intl.DateTimeFormat("it-IT", {
    hour: "2-digit",
    minute: "2-digit",
  }).format(date);
  return `${datePart}, ${timePart}`;
}
