import { ActionIcon, Alert, Badge, Button, Card, Group, Modal, NumberInput, Select, SimpleGrid, Stack, Stepper, Table, Text, TextInput, Title } from "@mantine/core";
import { notifications } from "@mantine/notifications";
import { IconCheck, IconExternalLink, IconFileExport, IconPencilPlus, IconRobot, IconTrash } from "@tabler/icons-react";
import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { api } from "../api/client";
import FormationPitch, { formationSlots, type FormationAssignments, type FormationSlot } from "../components/FormationPitch";
import PageLoader from "../components/PageLoader";
import type { GeneratedMatchPlanExport, MatchPeriod, MatchPlan as MatchPlanType, Player, RolePolicy, TeamEvent } from "../types";
import { formatDatesInText, formatDisplayDate } from "../utils/date";

const SLOT_LABELS: Record<string, string> = { portiere: "Portiere", difensoreSinistro: "Difensore sinistro", difensoreDestro: "Difensore destro", centrale: "Centrocampista", fasciaSinistra: "Fascia sinistra", fasciaDestra: "Fascia destra", attaccante: "Attaccante" };
type PlanForm = { name: string; periodCount: number; minutesPerPeriod: number; playersOnField: number; rolePolicy: RolePolicy };
const defaultForm: PlanForm = { name: "", periodCount: 3, minutesPerPeriod: 20, playersOnField: 7, rolePolicy: "preferred" };
function slotsForPlan(playersOnField: number): Array<[string, string]> { return playersOnField === 7 ? formationSlots.map(([slot, label]) => [slot, label]) : [["portiere", "Portiere"], ...Array.from({ length: playersOnField - 1 }, (_, index) => [`movimento${index + 1}`, "Giocatore di movimento"] as [string, string])]; }

export default function MatchPlan() {
  const eventId = Number(useParams<{ id: string }>().id);
  const [event, setEvent] = useState<TeamEvent | null>(null); const [players, setPlayers] = useState<Player[]>([]); const [teamName, setTeamName] = useState("");
  const [plans, setPlans] = useState<MatchPlanType[]>([]); const [selected, setSelected] = useState<MatchPlanType | null>(null); const [draftPeriods, setDraftPeriods] = useState<MatchPeriod[]>([]);
  const [form, setForm] = useState<PlanForm>(defaultForm); const [activePeriod, setActivePeriod] = useState(0); const [editingSlot, setEditingSlot] = useState<FormationSlot | null>(null);
  const [loading, setLoading] = useState(true); const [generating, setGenerating] = useState(false); const [creatingManual, setCreatingManual] = useState(false); const [saving, setSaving] = useState(false); const [exporting, setExporting] = useState(false); const [exportedDocument, setExportedDocument] = useState<GeneratedMatchPlanExport | null>(null); const [error, setError] = useState<string | null>(null);
  const selectPlan = (plan: MatchPlanType) => { setSelected(plan); setDraftPeriods(structuredClone(plan.periods)); setActivePeriod(0); setExportedDocument(null); setError(null); };
  const load = async () => {
    const [eventRes, playersRes, plansRes, configRes, settingsRes] = await Promise.all([api.getEvent(eventId), api.getPlayers(), api.getMatchPlans(eventId), api.getAIConfig(), api.getSettings()]);
    const configured = { name: "", periodCount: configRes.data.defaultPeriodCount, minutesPerPeriod: configRes.data.defaultMinutesPerPeriod, playersOnField: configRes.data.defaultPlayersOnField, rolePolicy: configRes.data.defaultRolePolicy };
    setEvent(eventRes.data); setPlayers(playersRes.data); setPlans(plansRes.data); setTeamName(settingsRes.data.teamName); setForm(configured); if (plansRes.data[0]) selectPlan(plansRes.data[0]);
  };
  useEffect(() => { load().catch(() => setError("Impossibile caricare i dati della partita")).finally(() => setLoading(false)); }, [eventId]);
  const createPlan = async (kind: "ai" | "manual") => {
    if (kind === "ai") setGenerating(true); else setCreatingManual(true); setError(null);
    try { const response = kind === "ai" ? await api.generateMatchPlan(eventId, form) : await api.createManualMatchPlan(eventId, form); setPlans((current) => [response.data, ...current]); selectPlan(response.data); notifications.show({ color: response.data.source === "ai" ? "green" : "blue", message: kind === "ai" ? (response.data.source === "ai" ? "Piano generato dall’AI" : "Applicata la rotazione automatica locale") : "Piano manuale creato" }); }
    catch (err) { setError((err as { response?: { data?: { error?: string } } }).response?.data?.error ?? "Creazione non riuscita"); }
    finally { if (kind === "ai") setGenerating(false); else setCreatingManual(false); }
  };
  const currentPeriod = draftPeriods[activePeriod]; const planSlots = selected ? slotsForPlan(selected.playersOnField) : [];
  const assignmentFor = (slot: string) => currentPeriod?.assignments.find((assignment) => assignment.slot === slot);
  const updatePlayer = (slot: string, playerId: number | null) => {
    if (!selected) return; setDraftPeriods((current) => current.map((period, index) => {
      if (index !== activePeriod) return period; const role = SLOT_LABELS[slot] ?? planSlots.find(([candidate]) => candidate === slot)?.[1] ?? "Giocatore di movimento"; const withoutSlot = period.assignments.filter((assignment) => assignment.slot !== slot);
      const assignments = (playerId === null ? withoutSlot : [...withoutSlot.filter((assignment) => assignment.playerId !== playerId), { slot, playerId, role }]).sort((a, b) => planSlots.findIndex(([candidate]) => candidate === a.slot) - planSlots.findIndex(([candidate]) => candidate === b.slot));
      const used = new Set(assignments.map((assignment) => assignment.playerId)); return { ...period, assignments, benchPlayerIds: players.map((player) => player.id).filter((id) => !used.has(id)) };
    }));
  };
  const saveManual = async () => { if (!selected) return; setSaving(true); setError(null); try { const response = await api.updateMatchPlan(eventId, selected.id, { periods: draftPeriods }); setSelected(response.data); setPlans((current) => current.map((plan) => plan.id === response.data.id ? response.data : plan)); notifications.show({ color: "green", message: "Modifiche salvate" }); } catch (err) { setError((err as { response?: { data?: { error?: string } } }).response?.data?.error ?? "Completa le formazioni prima di salvare"); } finally { setSaving(false); } };
  const confirm = async () => { if (!selected) return; setError(null); try { const response = await api.confirmMatchPlan(eventId, selected.id); setSelected(response.data); setPlans((current) => current.map((plan) => plan.id === response.data.id ? response.data : plan)); notifications.show({ color: "green", message: "Piano partita confermato" }); } catch (err) { setError((err as { response?: { data?: { error?: string } } }).response?.data?.error ?? "Conferma non riuscita"); } };
  const exportPlan = async () => { if (!selected) return; setExporting(true); setError(null); try { const response = await api.exportMatchPlan(eventId, selected.id); setExportedDocument(response.data); notifications.show({ color: "green", message: "Piano partita esportato in Google Docs" }); } catch (err) { setError((err as { response?: { data?: { error?: string } } }).response?.data?.error ?? "Esportazione in Google Docs non riuscita"); } finally { setExporting(false); } };
  const remove = async (plan: MatchPlanType) => { if (!window.confirm(`Eliminare “${plan.name}”?`)) return; await api.deleteMatchPlan(eventId, plan.id); const next = plans.filter((item) => item.id !== plan.id); setPlans(next); if (next[0]) selectPlan(next[0]); else { setSelected(null); setDraftPeriods([]); } };
  const summary = players.map((player) => { const appearances = draftPeriods.reduce((count, period) => count + (period.assignments.some((assignment) => assignment.playerId === player.id) ? 1 : 0), 0); const roles = [...new Set(draftPeriods.flatMap((period) => period.assignments.filter((assignment) => assignment.playerId === player.id).map((assignment) => assignment.role)))]; return { player, appearances, minutes: appearances * (selected?.minutesPerPeriod ?? 0), roles }; });
  const hasIncompletePeriods = selected ? draftPeriods.some((period) => period.assignments.length !== selected.playersOnField) : false;
  const usedElsewhere = new Set((currentPeriod?.assignments ?? []).filter((assignment) => assignment.slot !== editingSlot).map((assignment) => assignment.playerId));
  const editorAssignments = useMemo(() => Object.fromEntries(formationSlots.map(([slot]) => [slot, assignmentFor(slot)?.playerId ?? null])) as FormationAssignments, [currentPeriod]);
  if (loading) return <PageLoader />;
  return <Stack gap="lg">
    <Group justify="space-between"><div><Title order={3}>Piano partita</Title><Text c="dimmed">{formatDisplayDate(event?.date)}{event?.opponent ? ` · ${teamName} vs ${event.opponent}` : ""}</Text></div><Button component={Link} to={`/events/${eventId}`} variant="subtle">Torna all’evento</Button></Group>
    {error && <Alert color="red" title="Errore">{error}</Alert>}
    <Card withBorder padding="lg"><Stack><Group><IconPencilPlus /><Title order={4}>Crea piano partita</Title></Group><Text size="sm" c="dimmed">Crea una bozza da compilare sul campo oppure chiedi all’AI una proposta bilanciata per minutaggi, ruoli, piede preferito e caratteristiche tecniche.</Text><PlanFields form={form} setForm={setForm} /><Group><Button variant="light" leftSection={<IconPencilPlus size={18} />} onClick={() => void createPlan("manual")} loading={creatingManual} disabled={players.length < form.playersOnField}>Crea manualmente</Button><Button leftSection={<IconRobot size={18} />} onClick={() => void createPlan("ai")} loading={generating} disabled={players.length < form.playersOnField}>Genera con AI</Button></Group></Stack></Card>
    {plans.length > 0 && <Group align="flex-start" wrap="wrap"><Stack gap="xs" w={{ base: "100%", md: 250 }}>{plans.map((plan) => <Card key={plan.id} withBorder onClick={() => selectPlan(plan)} style={{ cursor: "pointer", borderColor: selected?.id === plan.id ? "var(--mantine-primary-color-filled)" : undefined }}><Group justify="space-between" wrap="nowrap"><div><Text fw={600}>{formatDatesInText(plan.name)}</Text><Group gap={4}><Badge size="xs" color={plan.source === "ai" ? "green" : plan.source === "manual" ? "blue" : "yellow"}>{plan.source}</Badge><Badge size="xs" variant="light">{plan.status}</Badge></Group></div><ActionIcon color="red" variant="subtle" onClick={(clickEvent) => { clickEvent.stopPropagation(); void remove(plan); }} aria-label="Elimina piano"><IconTrash size={16} /></ActionIcon></Group></Card>)}</Stack>
      {selected && <Stack style={{ flex: 1, minWidth: 0 }}>
        {selected.warnings.map((warning) => <Alert key={warning} color="yellow">{warning}</Alert>)}
        <Card withBorder padding="lg"><Stack gap="md"><Group justify="space-between"><div><Title order={4}>Formazione per tempo</Title><Text size="sm" c="dimmed">Tocca una posizione sul campo per assegnare o sostituire un giocatore.</Text></div><Badge variant="light" color={currentPeriod?.assignments.length === selected.playersOnField ? "green" : "yellow"}>{currentPeriod?.assignments.length ?? 0}/{selected.playersOnField} in campo</Badge></Group><Stepper active={activePeriod} onStepClick={setActivePeriod} allowNextStepsSelect orientation="horizontal" size="sm">{draftPeriods.map((period) => <Stepper.Step key={period.periodNumber} label={`Tempo ${period.periodNumber}`} description={`${selected.minutesPerPeriod} min`} />)}</Stepper>
          {selected.playersOnField === 7 ? <FormationPitch assignments={editorAssignments} players={players} onSlotClick={(slot) => setEditingSlot(slot)} ariaLabel={`Formazione del tempo ${(currentPeriod?.periodNumber ?? 0)}`} /> : <SimpleGrid cols={{ base: 1, sm: 2 }}>{planSlots.map(([slot, label]) => <Select key={slot} label={label} data={players.map((player) => ({ value: String(player.id), label: player.name, disabled: usedElsewhere.has(player.id) && assignmentFor(slot)?.playerId !== player.id }))} value={assignmentFor(slot) ? String(assignmentFor(slot)?.playerId) : null} onChange={(value) => updatePlayer(slot, value ? Number(value) : null)} clearable searchable />)}</SimpleGrid>}
          <Text size="sm" c="dimmed">Panchina: {currentPeriod?.benchPlayerIds.map((id) => players.find((player) => player.id === id)?.name).filter(Boolean).join(", ") || "nessuno"}</Text></Stack></Card>
        <Card withBorder><Title order={5} mb="sm">Riepilogo minutaggio</Title><Table.ScrollContainer minWidth={500}><Table striped><Table.Thead><Table.Tr><Table.Th>Giocatore</Table.Th><Table.Th>Tempi</Table.Th><Table.Th>Minuti</Table.Th><Table.Th>Ruoli</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{summary.map((row) => <Table.Tr key={row.player.id}><Table.Td>{row.player.name}</Table.Td><Table.Td>{row.appearances}</Table.Td><Table.Td>{row.minutes}</Table.Td><Table.Td>{row.roles.join(", ") || "—"}</Table.Td></Table.Tr>)}</Table.Tbody></Table></Table.ScrollContainer></Card>
        {hasIncompletePeriods && <Alert color="yellow">Puoi salvare una bozza parziale; completa tutti i tempi prima di confermare o esportare il piano.</Alert>}<Group><Button onClick={saveManual} loading={saving}>Salva modifiche</Button><Button color="green" leftSection={<IconCheck size={18} />} onClick={confirm} disabled={selected.status === "confirmed" || hasIncompletePeriods}>Conferma piano</Button><Button variant="light" leftSection={<IconFileExport size={18} />} onClick={exportPlan} loading={exporting} disabled={hasIncompletePeriods}>Esporta in Google Docs</Button></Group>
        {exportedDocument && <Alert color="green" title="Piano partita esportato"><Text size="sm" mb="xs">{exportedDocument.title}</Text><Button component="a" href={exportedDocument.googleDocUrl} target="_blank" rel="noopener noreferrer" size="compact-sm" variant="light" rightSection={<IconExternalLink size={15} />}>Apri documento Google</Button></Alert>}
      </Stack>}
    </Group>}
    {plans.length === 0 && <Text c="dimmed">Non è ancora stato creato alcun piano per questa partita.</Text>}
    <Modal opened={editingSlot !== null} onClose={() => setEditingSlot(null)} title={editingSlot ? SLOT_LABELS[editingSlot] : ""} centered><Stack>{editingSlot && <Select label="Giocatore" placeholder="Seleziona giocatore" data={players.map((player) => ({ value: String(player.id), label: player.name, disabled: usedElsewhere.has(player.id) }))} value={assignmentFor(editingSlot) ? String(assignmentFor(editingSlot)?.playerId) : null} onChange={(value) => { updatePlayer(editingSlot, value ? Number(value) : null); setEditingSlot(null); }} searchable />}{editingSlot && assignmentFor(editingSlot) && <Button variant="subtle" color="red" onClick={() => { updatePlayer(editingSlot, null); setEditingSlot(null); }}>Rimuovi giocatore</Button>}</Stack></Modal>
  </Stack>;
}
function PlanFields({ form, setForm }: { form: PlanForm; setForm: React.Dispatch<React.SetStateAction<PlanForm>> }) { return <SimpleGrid cols={{ base: 1, sm: 2, xl: 3 }}><TextInput label="Nome" placeholder="Piano partita" value={form.name} onChange={(event) => setForm({ ...form, name: event.currentTarget.value })} /><NumberInput label="Tempi" min={1} max={12} value={form.periodCount} onChange={(value) => setForm({ ...form, periodCount: Number(value) })} /><NumberInput label="Minuti/tempo" min={1} max={90} value={form.minutesPerPeriod} onChange={(value) => setForm({ ...form, minutesPerPeriod: Number(value) })} /><NumberInput label="In campo" min={2} max={11} value={form.playersOnField} onChange={(value) => setForm({ ...form, playersOnField: Number(value) })} /><Select label="Ruoli" data={[{ value: "strict", label: "Rigidi" }, { value: "preferred", label: "Preferiti" }, { value: "free", label: "Liberi" }]} value={form.rolePolicy} onChange={(value) => setForm({ ...form, rolePolicy: (value ?? "preferred") as RolePolicy })} /></SimpleGrid>; }
